object Library {

    const val kotlin_stdlib = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4.0"
    const val kotlin_coroutines_core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.1"
    const val kotlin_coroutines_android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.1"
    const val material = "com.google.android.material:material:1.3.0-alpha03"
    const val appcompat = "androidx.appcompat:appcompat:1.2.0"
    const val activity_ktx = "androidx.activity:activity-ktx:1.1.0"
    const val fragment_ktx = "androidx.fragment:fragment-ktx:1.2.5"
    const val collection_ktx = "androidx.collection:collection-ktx:1.1.0"
    const val navigation_fragment_ktx = "androidx.navigation:navigation-fragment-ktx:2.3.1"
    const val navigation_ui_ktx = "androidx.navigation:navigation-ui-ktx:2.3.1"
    const val viewmodel_ktx = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
    const val livedata_ktx = "androidx.lifecycle:lifecycle-livedata-ktx:2.2.0"
    const val work_ktx = "androidx.work:work-runtime-ktx:2.4.0"
    const val room_ktx = "androidx.room:room-ktx:2.2.5"
    const val room_compiler = "androidx.room:room-compiler:2.2.5"
    const val startup = "androidx.startup:startup-runtime:1.0.0"
    const val viewpager2 = "androidx.viewpager2:viewpager2:1.0.0"
    const val constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"
    const val recyclerview = "androidx.recyclerview:recyclerview:1.2.0-alpha05"
    const val mmkv = "com.tencent:mmkv-static:1.2.4"
    const val timber = "com.jakewharton.timber:timber:4.7.1"
    const val utdid = "com.taobao.android:utdid4all:1.1.5"
    const val lottie = "com.airbnb.android:lottie:3.5.0"
    const val smartrefreshlayout = "com.scwang.smart:refresh-layout-kernel:2.0.1"
    const val smartrefreshlayout_header = "com.scwang.smart:refresh-header-classics:2.0.1"
    const val smartrefreshlayout_footer = "com.scwang.smart:refresh-footer-classics:2.0.1"
    const val retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
    const val retrofit_moshi = "com.squareup.retrofit2:converter-moshi:2.9.0"
    const val okhttp = "com.squareup.okhttp3:okhttp:4.9.0"
    const val okhttp_logging_interceptor = "com.squareup.okhttp3:logging-interceptor:4.9.0"
    const val moshi = "com.squareup.moshi:moshi-kotlin:1.11.0"
    const val moshi_kapt = "com.squareup.moshi:moshi-kotlin-codegen:1.11.0"
    const val coil = "io.coil-kt:coil:1.0.0"
    const val multidex = "androidx.multidex:multidex:2.0.1"
    const val arouter = "com.alibaba:arouter-api:1.5.1"
    const val arouter_compiler = "com.alibaba:arouter-compiler:1.5.1"
    const val picture_selector = "com.github.LuckSiege.PictureSelector:picture_library:v2.5.9"

}